using System.Text.Json.Serialization;
using OpenRouterClient.DTO;
using OpenRouterClient.DTO.Request;

public class ChoiceDto
{
    /// <summary>
    /// Optional. The message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public MessageDto Message { get; set; }
}